@startuml CreateZustandsdiagramm

state "Create.tsx" as Create {
  state "Formular" as Formular {
    state "Input" as Input
    state "Validation" as Validation
    state "Valid" as Valid
    state "Invalid" as Invalid


  }

  state "Waiting" as Waiting
  state "CreationSuccess" as CreationSuccess
  state "CreationError" as CreationError

  Waiting --> CreationSuccess: Erfolgreiche Erstellung
  Waiting --> CreationError: Fehlgeschlagene Erstellung
  CreationError --> Formular: Fehlermeldung und Neueingabe
  CreationSuccess --> [*]: Meldung Successfull
}

@enduml