@startuml LoginZustandsdiagramm

state "Login.tsx" as Login {
  state "LoginForm" as LoginForm
  state "Waiting" as Waiting
  state "LoginSuccess" as LoginSuccess
  state "LoginError" as LoginError

  [*] --> LoginForm: Seite geladen
  LoginForm --> Waiting: Button "Login"
  Waiting --> LoginSuccess: Erfolgreiche Authentifizierung
  Waiting --> LoginError: Fehlgeschlagene Authentifizierung
  LoginError --> LoginForm: Löschen der falschen daten und neues eingeben
  LoginSuccess --> [*]: Weiterleitung zur Hauptseite
}

@enduml