@startuml Zustandsdiagramm

state "search.tsx" as index {
  state "SucheBuecher" as SucheBuecher {
    state "Suchformular" as Suchformular
    state "Waiting" as Waiting
    state "SuchergebnisChoice" as SuchergebnisChoice
    state "Suchergebnis" as Suchergebnis {
      state "GefundeneBuecher" as GefundeneBuecher
      state "ErrorMessage" as ErrorMessage
    }
    state "DetailsBuch" as DetailsBuch
  }

  [*] --> index: login
  index --> SucheBuecher: Menüpunkt "Suche"
  SucheBuecher --> Suchformular: Suchkritierien
  Suchformular --> Waiting: Button "Suchen"
  Waiting --> SuchergebnisChoice: Suchergebisse eingetroffen
  SuchergebnisChoice --> GefundeneBuecher: mind ein Buch
  SuchergebnisChoice --> ErrorMessage: keine Bücher
  GefundeneBuecher --> DetailsBuch: Button anklicken
  DetailsBuch --> [*]
}

@enduml